require("plugins.aerial")
require("plugins.autopairs")
require("plugins.blink_cmp")
require("plugins.conform")
require("plugins.dropbar")
require("plugins.img-clip")
require("plugins.lsp")
require("plugins.lualine")
require("plugins.oil")
require("plugins.go")
require("plugins.peek-md")
require("plugins.rainbow")

require("plugins.smear-cursor")
require("plugins.snacks")
require("plugins.supermaven")
require("plugins.surround")
require("plugins.telescope")
require("plugins.toggler")
require("plugins.toggleterm")
require("plugins.treesitter")
require("plugins.which-key")

