require("plugins.autopairs")
require("plugins.blink_cmp")
require("plugins.lsp")
require("plugins.mason")
require("plugins.neo_tree")
require("plugins.oil")
require("plugins.scissors")
require("plugins.telescope")
require("plugins.treesitter")

