require("plugins.aerial")
require("plugins.autopairs")
require("plugins.blink_cmp")
require("plugins.conform")
require("plugins.dap")
require("plugins.dropbar")
require("plugins.img-clip")
require("plugins.indentline")
require("plugins.inlayhints")
require("plugins.lsp")
require("plugins.lualine")
require("plugins.mason")
-- require("plugins.multicursor")
require("plugins.neo_tree")
require("plugins.notify")
require("plugins.oil")
require("plugins.peek")
-- require("plugins.render-markdown")
require("plugins.scissors")
require("plugins.smear-cursor")
require("plugins.surround")
require("plugins.telescope")
require("plugins.toggler")
require("plugins.toggleterm")
require("plugins.treesitter")
require("plugins.yanky")
